### ISSUE TITLE
Including version numbers

### ISSUE THREAD

**Issue by blazman** [SAFETAG/SAFETAG#406]
Suggesting that there be a Version file incremented by the maintainers on major merges which gets included on the front page. As these things still need to be built manually it will help us in the community to know which version is current, if there is new content on Github in front of published versions, and will help users to know if there is a newer version they can be using.

**Comment by joncamfield** [comment]
From a process standpoint, the "releases" are versioned, but that doesn't show up in the guide itself.  In some ideal git world, we'd say that the "master" branch is only updated (merged from dev ?) for a release, and a version number is added to the master index.guide.md at that time.  This could confuse editing/github processes however; so perhaps we instead make a new branch ("publish" ?) which we merge from master when we make a release and do that there.

Before advancing this, let's see where the new website work lands in terms of if PDFs are built from there instead of DocBuilder, and if that would differently "manage" versions ?

**Comment by blazman** [comment]
Latest recommendation on this is to simply put 'PDF Generated on {DATE}' on the PDF frontpage, and preferably have the latest version generated on a schedule (see #435)
